import { IncidentData, PostmortemResult, SeverityInfo } from '@/types';

function buildMarkdown(parsed: Omit<PostmortemResult, 'markdown' | 'confluenceFormat'>): string {
  const { title, severity, summary, timeline, timelineGaps, rootCauseChain, contributingFactors, whatWentWell, whatWentWrong, actionItems } = parsed;

    const severityBadge = `[${severity.level}]`;

      let md = `# ${severityBadge} Post-Mortem: ${title}\n\n`;
        md += `**Generated:** ${parsed.generatedAt}  \n`;
          md += `**Service:** ${parsed.rawInput.serviceName}  \n`;
            md += `**Period:** ${parsed.rawInput.timeRange}  \n\n`;
              md += `---\n\n`;

                md += `## Executive Summary\n\n${summary}\n\n`;
                  md += `**Severity:** ${severity.level} — ${severity.reasoning}\n\n`;

                    md += `---\n\n## Timeline of Events\n\n`;
                      if (timelineGaps.length > 0) {
                          md += `> ⚠️ **${timelineGaps.length} timeline gap(s) detected** — see gaps section below\n\n`;
                            }
                              md += `| Time (UTC) | Event | Source |\n`;
                                md += `|------------|-------|--------|\n`;
                                  for (const event of timeline) {
                                      md += `| ${event.time} | ${event.event} | ${event.source} |\n`;
                                        }
                                          md += `\n`;

                                            if (timelineGaps.length > 0) {
                                                md += `### ⚠️ Timeline Gaps\n\n`;
                                                    for (const gap of timelineGaps) {
                                                          md += `- **${gap.from} → ${gap.to}** (${gap.durationMinutes} min): ${gap.note}\n`;
                                                              }
                                                                  md += `\n`;
                                                                    }

                                                                      md += `---\n\n## Root Cause Chain\n\n${rootCauseChain}\n\n`;

                                                                        md += `---\n\n## Contributing Factors\n\n`;
                                                                          for (const factor of contributingFactors) {
                                                                              md += `- ${factor}\n`;
                                                                                }
                                                                                  md += `\n`;

                                                                                    md += `---\n\n## What Went Well\n\n`;
                                                                                      for (const item of whatWentWell) {
                                                                                          md += `- ✅ ${item}\n`;
                                                                                            }
                                                                                              md += `\n`;

                                                                                                md += `---\n\n## What Went Wrong\n\n`;
                                                                                                  for (const item of whatWentWrong) {
                                                                                                      md += `- ❌ ${item}\n`;
                                                                                                        }
                                                                                                          md += `\n`;
                                                                                                          
                                                                                                            md += `---\n\n## Action Items\n\n`;
                                                                                                              md += `| # | Action | Owner | Due | Priority |\n`;
                                                                                                                md += `|---|--------|-------|-----|----------|\n`;
                                                                                                                  for (const item of actionItems) {
                                                                                                                      const priorityEmoji = item.priority === 'high' ? '🔴' : item.priority === 'medium' ? '🟡' : '🟢';
                                                                                                                          md += `| ${item.id} | ${item.title} | ${item.owner} | ${item.dueDate} | ${priorityEmoji} ${item.priority} |\n`;
                                                                                                                            }
                                                                                                                              md += `\n`;
                                                                                                                              
                                                                                                                                md += `---\n\n*This post-mortem was generated by Postmortem Autopilot. Review and edit before publishing.*\n`;
                                                                                                                                
                                                                                                                                  return md;
                                                                                                                                  }
                                                                                                                                  
                                                                                                                                  function buildConfluenceFormat(parsed: Omit<PostmortemResult, 'markdown' | 'confluenceFormat'>): string {
                                                                                                                                    const { title, severity, summary, timeline, timelineGaps, rootCauseChain, contributingFactors, whatWentWell, whatWentWrong, actionItems } = parsed;
                                                                                                                                    
                                                                                                                                      let cf = `h1. [${severity.level}] Post-Mortem: ${title}\n\n`;
                                                                                                                                        cf += `*Generated:* ${parsed.generatedAt}\\\\\\n`;
                                                                                                                                          cf += `*Service:* ${parsed.rawInput.serviceName}\\\\\\n`;
                                                                                                                                            cf += `*Period:* ${parsed.rawInput.timeRange}\\\\\\n\n`;
                                                                                                                                            
                                                                                                                                              cf += `----\n\nh2. Executive Summary\n\n${summary}\n\n`;
                                                                                                                                                cf += `*Severity:* ${severity.level} — ${severity.reasoning}\n\n`;
                                                                                                                                                
                                                                                                                                                  cf += `----\n\nh2. Timeline of Events\n\n`;
                                                                                                                                                    if (timelineGaps.length > 0) {
                                                                                                                                                        cf += `{warning}${timelineGaps.length} timeline gap(s) detected — see gaps section below{warning}\n\n`;
                                                                                                                                                          }
                                                                                                                                                            cf += `|| Time (UTC) || Event || Source ||\n`;
                                                                                                                                                              for (const event of timeline) {
                                                                                                                                                                  cf += `| ${event.time} | ${event.event} | ${event.source} |\n`;
                                                                                                                                                                    }
                                                                                                                                                                      cf += `\n`;
                                                                                                                                                                      
                                                                                                                                                                        if (timelineGaps.length > 0) {
                                                                                                                                                                            cf += `h3. Timeline Gaps\n\n`;
                                                                                                                                                                                for (const gap of timelineGaps) {
                                                                                                                                                                                      cf += `* *${gap.from} -> ${gap.to}* (${gap.durationMinutes} min): ${gap.note}\n`;
                                                                                                                                                                                          }
                                                                                                                                                                                              cf += `\n`;
                                                                                                                                                                                                }
                                                                                                                                                                                                
                                                                                                                                                                                                  cf += `----\n\nh2. Root Cause Chain\n\n${rootCauseChain}\n\n`;
                                                                                                                                                                                                  
                                                                                                                                                                                                    cf += `----\n\nh2. Contributing Factors\n\n`;
                                                                                                                                                                                                      for (const factor of contributingFactors) {
                                                                                                                                                                                                          cf += `* ${factor}\n`;
                                                                                                                                                                                                            }
                                                                                                                                                                                                              cf += `\n`;
                                                                                                                                                                                                              
                                                                                                                                                                                                                cf += `----\n\nh2. What Went Well\n\n`;
                                                                                                                                                                                                                  for (const item of whatWentWell) {
                                                                                                                                                                                                                      cf += `* (/) ${item}\n`;
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                          cf += `\n`;
                                                                                                                                                                                                                          
                                                                                                                                                                                                                            cf += `----\n\nh2. What Went Wrong\n\n`;
                                                                                                                                                                                                                              for (const item of whatWentWrong) {
                                                                                                                                                                                                                                  cf += `* (x) ${item}\n`;
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                      cf += `\n`;
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                        cf += `----\n\nh2. Action Items\n\n`;
                                                                                                                                                                                                                                          cf += `|| # || Action || Owner || Due || Priority ||\n`;
                                                                                                                                                                                                                                            for (const item of actionItems) {
                                                                                                                                                                                                                                                cf += `| ${item.id} | ${item.title} | ${item.owner} | ${item.dueDate} | ${item.priority.toUpperCase()} |\n`;
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                    cf += `\n\n_This post-mortem was generated by Postmortem Autopilot. Review and edit before publishing._\n`;
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                      return cf;
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                      export function parsePostmortem(rawText: string, inputData: IncidentData): PostmortemResult {
                                                                                                                                                                                                                                                        let jsonStr = rawText.trim();
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                          // Strip markdown code fences if present
                                                                                                                                                                                                                                                            if (jsonStr.startsWith('```')) {
                                                                                                                                                                                                                                                                jsonStr = jsonStr.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '');
                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                    let parsed: Record<string, unknown>;
                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                          parsed = JSON.parse(jsonStr);
                                                                                                                                                                                                                                                                            } catch {
                                                                                                                                                                                                                                                                                // Try to extract JSON from the text
                                                                                                                                                                                                                                                                                    const match = jsonStr.match(/\{[\s\S]*\}/);
                                                                                                                                                                                                                                                                                        if (match) {
                                                                                                                                                                                                                                                                                              parsed = JSON.parse(match[0]);
                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                        throw new Error('Could not parse JSON response from AI');
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                const severityLevel = (parsed.severity as Record<string, string>)?.level as 'P1' | 'P2' | 'P3';
                                                                                                                                                                                                                                                                                                                  const severityColors: Record<string, string> = {
                                                                                                                                                                                                                                                                                                                      P1: 'red',
                                                                                                                                                                                                                                                                                                                          P2: 'orange',
                                                                                                                                                                                                                                                                                                                              P3: 'yellow',
                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                  const severity: SeverityInfo = {
                                                                                                                                                                                                                                                                                                                                      level: severityLevel || 'P2',
                                                                                                                                                                                                                                                                                                                                          reasoning: (parsed.severity as Record<string, string>)?.reasoning || '',
                                                                                                                                                                                                                                                                                                                                              color: severityColors[severityLevel] || 'orange',
                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                  const generatedAt = new Date().toISOString();
                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                    const base = {
                                                                                                                                                                                                                                                                                                                                                        title: (parsed.title as string) || 'Incident Post-Mortem',
                                                                                                                                                                                                                                                                                                                                                            severity,
                                                                                                                                                                                                                                                                                                                                                                summary: (parsed.summary as string) || '',
                                                                                                                                                                                                                                                                                                                                                                    timeline: (parsed.timeline as PostmortemResult['timeline']) || [],
                                                                                                                                                                                                                                                                                                                                                                        timelineGaps: (parsed.timelineGaps as PostmortemResult['timelineGaps']) || [],
                                                                                                                                                                                                                                                                                                                                                                            rootCauseChain: (parsed.rootCauseChain as string) || '',
                                                                                                                                                                                                                                                                                                                                                                                contributingFactors: (parsed.contributingFactors as string[]) || [],
                                                                                                                                                                                                                                                                                                                                                                                    whatWentWell: (parsed.whatWentWell as string[]) || [],
                                                                                                                                                                                                                                                                                                                                                                                        whatWentWrong: (parsed.whatWentWrong as string[]) || [],
                                                                                                                                                                                                                                                                                                                                                                                            actionItems: (parsed.actionItems as PostmortemResult['actionItems']) || [],
                                                                                                                                                                                                                                                                                                                                                                                                rawInput: inputData,
                                                                                                                                                                                                                                                                                                                                                                                                    generatedAt,
                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                        const markdown = buildMarkdown(base);
                                                                                                                                                                                                                                                                                                                                                                                                          const confluenceFormat = buildConfluenceFormat(base);
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                ...base,
                                                                                                                                                                                                                                                                                                                                                                                                                    markdown,
                                                                                                                                                                                                                                                                                                                                                                                                                        confluenceFormat,
                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                          }
