'use client';

import { useState } from 'react';
import IncidentForm from '@/components/IncidentForm';
import PostmortemOutput from '@/components/PostmortemOutput';
import { IncidentData, PostmortemResult } from '@/types';

export default function Home() {
  const [result, setResult] = useState<PostmortemResult | null>(null);
    const [loading, setLoading] = useState(false);
      const [error, setError] = useState<string | null>(null);

        const handleGenerate = async (data: IncidentData) => {
            setLoading(true);
                setError(null);
                    setResult(null);
                        try {
                              const response = await fetch('/api/generate', {
                                      method: 'POST',
                                              headers: { 'Content-Type': 'application/json' },
                                                      body: JSON.stringify(data),
                                                            });
                                                                  if (!response.ok) {
                                                                          const err = await response.json();
                                                                                  throw new Error(err.error || 'Generation failed');
                                                                                        }
                                                                                              const json = await response.json();
                                                                                                    setResult(json);
                                                                                                        } catch (e: unknown) {
                                                                                                              setError(e instanceof Error ? e.message : 'Unknown error');
                                                                                                                  } finally {
                                                                                                                        setLoading(false);
                                                                                                                            }
                                                                                                                              };
                                                                                                                              
                                                                                                                                return (
                                                                                                                                    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
                                                                                                                                          <div className="max-w-5xl mx-auto px-4 py-8">
                                                                                                                                                  <header className="text-center mb-10">
                                                                                                                                                            <div className="inline-flex items-center gap-2 bg-sky-500/10 border border-sky-500/20 rounded-full px-4 py-1.5 text-sky-400 text-sm font-medium mb-4">
                                                                                                                                                                        <span className="w-2 h-2 rounded-full bg-sky-400 animate-pulse"></span>
                                                                                                                                                                                    AI-Powered Incident Analysis
                                                                                                                                                                                              </div>
                                                                                                                                                                                                        <h1 className="text-4xl font-bold text-white mb-3">
                                                                                                                                                                                                                    Postmortem <span className="text-sky-400">Autopilot</span>
                                                                                                                                                                                                                              </h1>
                                                                                                                                                                                                                                        <p className="text-slate-400 text-lg max-w-2xl mx-auto">
                                                                                                                                                                                                                                                    Automatically generate blameless post-mortems from incident data.
                                                                                                                                                                                                                                                                Paste your signals, get a full draft in seconds.
                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                  </header>
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                          <IncidentForm onSubmit={handleGenerate} loading={loading} />
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                  {error && (
                                                                                                                                                                                                                                                                                                            <div className="mt-6 p-4 bg-red-500/10 border border-red-500/30 rounded-xl text-red-400">
                                                                                                                                                                                                                                                                                                                        <strong>Error:</strong> {error}
                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                  {loading && (
                                                                                                                                                                                                                                                                                                                                                            <div className="mt-8 text-center">
                                                                                                                                                                                                                                                                                                                                                                        <div className="inline-flex items-center gap-3 text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                      <div className="w-5 h-5 border-2 border-sky-400 border-t-transparent rounded-full animate-spin"></div>
                                                                                                                                                                                                                                                                                                                                                                                                    Analyzing incident signals and generating post-mortem...
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                          {result && <PostmortemOutput result={result} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
